### PR TITLE
Fix #145 Use official jasypt

### LINKED ISSUE #145: Melloware Jasypt uses a very old snapshot of Jasypt
As far as I can tell the melloware version of Jasypt, which this codebase is now using, is a 3 year old copy of the jasypt codebase from the sourceforge SVN server.  If I am wrong here please correct me.  If I am correct, could someone please explain the logic behind building higher level encryption support on top of this instead of on top the official jasypt guthub repo?  My project uses this library for database and property encryption and switching to an old snapshot of jasypt is concerning me.  Thanks.

### PR DESCRIPTION
**Pull request by tkalmar**
Update Dependencies to official jasypt 1.9.3,
fix test-config to use official IV Generatorclass

### CODE REVIEW

**Comment by melloware** [comment]
Good PR.  Don't forget to also commit changes to README.MD https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/README.md which has examples using my version of the IVGenerator etc.

**Comment by melloware** [comment]
Also don't forget to fix the tests in this project: https://github.com/ulisesbocchio/jasypt-spring-boot-samples

**Comment by famod** [comment]
@tkalmar Just a heads-up: It seems https://github.com/ulisesbocchio/jasypt-spring-boot-samples/blob/master/.travis.yml also needs the oraclejdk8 fix.

**Comment by ulisesbocchio** [comment]
thanks guys!

**Pull request merged**
